import { Link, useLocation } from 'react-router-dom';
import { useEffect, useState } from 'react';

export default function Layout({ children }) {
  const [open, setOpen] = useState(false);
  const [user, setUser] = useState(() => localStorage.getItem('obra_user'));
  const location = useLocation();
  useEffect(() => { const sync = () => setUser(localStorage.getItem('obra_user')); window.addEventListener('obra-auth', sync); return () => window.removeEventListener('obra-auth', sync); }, []);
  const close = () => setOpen(false);
  const logout = () => { localStorage.removeItem('obra_user'); localStorage.removeItem('obra_token'); setUser(null); close(); };
  const links = [['/', 'Inicio'], ['/servicios', 'Servicios'], ['/profesionales', 'Profesionales'], ['/proyectos', 'Proyectos'], ['/como-funciona', 'Cómo funciona']];
  return <><header className="header"><Link className="brand" to="/" onClick={close}><span className="brand-mark">⬢</span> OBRA <b>CONECTA</b></Link><button className="menu-btn" onClick={() => setOpen(!open)} aria-label="Menú">☰</button><nav className={open ? 'nav open' : 'nav'}>{links.map(([path, label]) => <Link key={path} className={location.pathname === path ? 'active' : ''} to={path} onClick={close}>{label}</Link>)}{user ? <><Link className="auth-link" to="/panel" onClick={close}>Mi panel</Link><Link className="auth-link" to="/cuenta" onClick={close}>Mi cuenta</Link><Link className="header-cta" to="/cotizar" onClick={close}>Publicar trabajo</Link><button className="header-cta" onClick={logout}>Salir</button></> : <><Link className="auth-link" to="/login" onClick={close}>Iniciar sesión</Link><Link className="header-cta" to="/registro" onClick={close}>Registrarse</Link></>}</nav></header><main>{children}</main><footer><div className="footer-grid"><div><div className="brand footer-brand"><span className="brand-mark">⬢</span> OBRA <b>CONECTA</b></div><p>Conectamos personas con profesionales para hacer realidad proyectos de construcción, remodelación y mejoramiento.</p><p className="muted">Tecnología que ayuda a construir mejores espacios.</p></div><div><h4>Explorar</h4><Link to="/">Inicio</Link><Link to="/servicios">Servicios</Link><Link to="/profesionales">Profesionales</Link><Link to="/proyectos">Proyectos</Link></div><div><h4>Empresa</h4><Link to="/nosotros">Quiénes somos</Link><Link to="/mision">Nuestra misión</Link><Link to="/vision">Nuestra visión</Link><Link to="/contacto">Contáctanos</Link></div><div><h4>Ayuda</h4><Link to="/como-funciona">Cómo funciona</Link><Link to="/faq">Preguntas frecuentes</Link></div></div><div className="copyright">© 2026 Obra Conecta · Todos los derechos reservados · Colombia</div></footer></>}
